### ISSUE TITLE
"git my" only returns 100 repos

### ISSUE THREAD

**Issue by jenius** [willfarrell/alfred-github-workflow#17]
Github returns these results paginated, so it needs to run through all the pages in order for this feature to be fully implemented :confused: 

I'll take a look and see if I can submit a PR to fix this soon

**Comment by willfarrell** [comment]
Thanks man. Looking forward to it.

**Comment by jenius** [comment]
Sadly, I am not much of a PHP guy so I'm not sure I'd rely on myself to do this :cry: I did take a look though!

**Comment by jenius** [comment]
From my research on the API itself, you can use the `per_page` querystring parameter to set the limit up to 100. Anywhere over that, you'd have to iterate pages to collect the results, which you can use the `page` param for.

I'm not exactly sure where that URL is and how it is built, but for quick relief, just adding the `per_page` and setting that to 100 will at least make this functionality a little more useful, returning 10 repos makes it more or less useless to anyone, sadly...

**Comment by willfarrell** [comment]
You're looking for `users.php` line `23`:`$url = "https://api.github.com/users/$username/$api";`

`https://developer.github.com/v3/repos/` `List user repositories`

let me know if that works.
