### ISSUE TITLE
Show owner of repo in results

### ISSUE THREAD

**Issue by geoffharcourt** [willfarrell/alfred-github-workflow#19]
For repositories that have been extensively forked (or just things like "spring" that have been used as names in multiple languages), it's useful to be able to see who the owner is in Github's results.

I'm proposing to show the results as "holman/dotfiles" rather than just "dotfiles".

**Comment by willfarrell** [comment]
Sounds like a useful feature, I'd be more than happy to merge a PR. You can fork the code from https://github.com/willfarrell/alfred-github-workflow
