### ISSUE TITLE
Add Update Support for Packal

### ISSUE THREAD

**Issue by macx** [willfarrell/alfred-github-workflow#20]
It would be nice to have this workflow in [Packal](http://www.packal.org/) in order to do proper updates. Any plans?

**Comment by willfarrell** [comment]
Writing a build script to streamline the Packal update process is planned, it's just finding the time. If you know of an existing system others are using that would help me this added in sooner.

**Comment by macx** [comment]
@willfarrell Sorry, I have no template for this process at the moment.
