### ISSUE TITLE
Enterprise Support

### ISSUE THREAD

**Issue by krohrsb** [willfarrell/alfred-github-workflow#24]
Either i missed it or there is no enterprise support yet. This would make my day...

**Comment by willfarrell** [comment]
Enterprise support yet, but you're welcome to submit a PR.

will Farrell
Esq. BASc EIT
Internet Security, Web Application Architect and Polyglot Developer
Electrical Engineer - University of Waterloo
Cell: (403) 797-0557
willfarrell.ca
PGP Key: willfarrell.ca/pgp.html
